---

- name: Push routing configuration to ASA device
  asa_config:
    src: "cloud_vpn/providers/asa/responder/{{ cloud_vpn_responder_provider }}/configure_routing_{{ cloud_vpn_routing }}.j2"
  delegate_to: responder
